# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Андрей Созыкин
email: sozykin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Занимаюсь образованием в Data Science и Big Data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.asozykin.ru" # the base hostname & protocol for your site
enforce_ssl: www.asozykin.ru
#twitter_username: jekyllrb
#github_username:  jekyll
include: ['_pages']
# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
paginate: 10
paginate_path: "/blog/page:num/"
